### ISSUE TITLE
Consider DELETING google-services.json file (Optional)

### ISSUE THREAD

**Issue by callebdev** [GXMUHATE/Android-app-with-firebase-database#1]
The `google-services-json` file [HERE](https://github.com/GXMUHATE/Android-app-with-firebase-database/blob/main/app/google-services.json) contains your API keys and there are some [discussions](https://stackoverflow.com/questions/36964276/is-google-services-json-confidential) about whether it is safe or not to keep it public.
Making this file public can cause people to access/modify/delete the data in your Firebase project if the Firebase security rules have not been defined or you are only using it for testing. But it's okay to share this `json`, as long as you define security rules.
Keeping private or referencing it to [.gitignore](https://git-scm.com/docs/gitignore) whenever you create a repository is a good practice.

**Comment by GXMUHATE** [comment]
Thank you @callebdev I will consider the advice.

**Comment by callebdev** [comment]
Thanks for your attention.
Without further ado, I will close this issue.
